const CONSTANTS = require('./constant');

const SUBROLES_ENUM = [CONSTANTS.UNDERGRADUATE, CONSTANTS.POSTGRADUATE, CONSTANTS.RESEARCH_SCHOLAR, CONSTANTS.ADMIN, CONSTANTS.TEACHING_STAFF, CONSTANTS.OPERATIONAL_STAFF];
module.exports = SUBROLES_ENUM;